---

- name: install icinga repo
  yum:
    name: "https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm"
    state: installed

- name: install epel-release repo
  yum:
    name: epel-release
    state: latest

- name: install icinga and related packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd
    - icinga
    - icinga-gui
    - nagios-plugins
    - nagios-plugins-ping
    - nagios-plugins-disk
    - nagios-plugins-procs
    - nagios-plugins-users
    - nagios-plugins-load
    - nagios-plugins-ssh
    - nagios-plugins-swap
    - nagios-plugins-http
    - nagios-plugins-dummy
    - policycoreutils-python

- name: set SELinux to Enforcing
  selinux:
    policy: targeted
    state: enforcing

- name: copy custom SELinux policy
  copy:
    src: icinga.pp
    dest: /tmp/icinga.pp
  register: copypolicy

- name: add custom SELinux policy
  command: /sbin/semodule -i /tmp/icinga.pp
  when: copypolicy.changed

- name: enable httpd
  systemd:
    name: httpd
    state: started
    enabled: yes

- name: enable icinga
  systemd:
    name: icinga
    state: started
    enabled: yes

- name: allow ports 22, 80, 443 through host firewall
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - http
    - https
    - ssh

- name: copy demo index HTML if no index exists
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0755
    force: no

- name: change owner of icinga/gui directory
  file:
    path: /var/log/icinga/gui
    state: directory
    owner: icinga
    group: icinga
    recurse: yes

- name: add apache user to icinga, icingacmd groups
  user:
    name: apache
    groups: icinga,icingacmd
    append: yes
  notify:
  - restart apache


...
